const express = require("express");
const router = express.Router();
const planController = require('../../controller/employerController/employerplanController');
const adminfunction = require('../../controller/adminController/adminfunction');
const mainadminRoute = express.Router();
const multer = require("multer");
mainadminRoute.get('/fetchplanbyemp/:employerId', planController.getPlansByEmployer);
mainadminRoute.post('/activateplans', planController.activateSubscription);
mainadminRoute.get('/getallplans', planController.getAllPlans);
mainadminRoute.get('/getplans:id', planController.getPlanById);
mainadminRoute.post('/createplan',  planController.createPlan);
mainadminRoute.put('/updateplan:id',  planController.updatePlan);
mainadminRoute.delete('/deleteplan:id', planController.deletePlan);
mainadminRoute.put('/approveemployer/:id',  adminfunction.approveSingleEmployer);
mainadminRoute.put('/approve-all',  adminfunction.approveAllEmployers);
mainadminRoute.put('/approveemployee/:id',  adminfunction.approveSingleEmployee);
mainadminRoute.put('/approveallemployee',  adminfunction.approveAllEmployee);
mainadminRoute.put('/approveemployeradmin/:id',  adminfunction.approveSingleEmployeradmin);
mainadminRoute.put('/approveallemployeradmin',  adminfunction.approveAllEmployeradmin);
mainadminRoute.put('/updateapprovejobs/:id',  adminfunction.updateJobStatus);
mainadminRoute.put('/updateallapprved',  adminfunction.updateapproved);
mainadminRoute.put('/updateblockstatus/:id',  adminfunction.blockunblockemployer);
mainadminRoute.put('/updateblockstatusemploye/:id',  adminfunction.blockunblockemployee);
mainadminRoute.put('/updateblockstatusemployeradmin/:id',  adminfunction.blockunblockemployeradmin);
mainadminRoute.put('/updateunlick',  adminfunction.updateallblock);
mainadminRoute.get('/getallemployers', adminfunction.getAllEmployers);

mainadminRoute.get('/getsubscribedemployers', adminfunction.getSubscribedEmployers);
// employeradminRoute.get('/fetchsubunitjobs/:applicantId', employeradminController.getJobsByApplicant);
module.exports = mainadminRoute;